apiVersion: v1
kind: Service
metadata:
  name: ai-engine-service
  namespace: default
spec:
  selector:
    app: ai-engine
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP
