apiVersion: v1
kind: Service
metadata:
  name: cpu-hog-service
  labels:
    app: cpu-hog
spec:
  selector:
    app: cpu-hog
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP